# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/go-xorm/cmd
    steps:
      - checkout

      - run: go get -t -d -v ./...
      - run: go test ./... -v -race -coverprofile=coverage-1.txt -covermode=atomic
      - run: go get -u github.com/wadey/gocovmerge
      - run: gocovmerge coverage-1.txt > coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)